import "./globals.css"
import { Inter } from "next/font/google"
import Header from "@/components/globals/Header"
import Footer from "@/components/globals/Footer"
import AuthProvider from "@/providers/AuthProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  navigator: [
    { name: "Home", path: "/" },
    { name: "Posts", path: "/posts" },
    { name: "Categories", path: "/categories" },
    { name: "Contact", path: "/contact" },
    { name: "Blog", path: "/blog" },
    { name: "About", path: "/about" },
  ],
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Header navigator={metadata.navigator} />
          <div className="w-full">{children}</div>
          <Footer navigator={metadata.navigator} />
        </AuthProvider>
      </body>
    </html>
  )
}
